# Overall title for pages.
title: "Software Technology"

# Email address, no mailto:
email: "gaurav.gupta@mq.edu.au"

# Files and directories that are not to be copied.
exclude:
  - Makefile
  - bin/
  - .Rproj.user/
  - makeNavigationList.py
  - portingToMarkdown/
  - workshops/
  - archive/
  - workHours.csv
  - imageMagick.md

# Turn on built-in syntax highlighting.
highlighter: rouge

markdown: kramdown

# required to build on heroku
exclude: [vendor]

# More › http://kramdown.gettalong.org/quickref.html
# Options › http://kramdown.gettalong.org/options.html
kramdown:
  input:          GFM
  # https://github.com/jekyll/jekyll/pull/4090
  syntax_highlighter: rouge

  # Rouge Highlighter in Kramdown › http://kramdown.gettalong.org/syntax_highlighter/rouge.html
  # span, block element options fall back to global
  syntax_highlighter_opts:
    # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: 'highlight'
    #line_numbers: true # bad idea, spans don't need linenos and would inherit this option
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
